### ISSUE TITLE
Is anybody have in common experience in this picture?

### ISSUE THREAD

**Issue by ronghaichuan** [xmtp/example-notification-server-go#26]
### Describe the bug

<img width="1434" alt="image" src="https://github.com/xmtp/example-notification-server-go/assets/20941005/d7f993dc-ed65-4406-9f22-0fd90b723fc7">

**Comment by snormore** [comment]
@ronghaichuan Thanks for reporting this, I was able to easily reproduce as well. I opened a PR to fix it here https://github.com/xmtp/example-notification-server-go/pull/27

**Comment by ronghaichuan** [comment]
awesome
