### ISSUE TITLE
Bug: when the delivery service fails for one request we should continue with the rest

### ISSUE THREAD

**Issue by neekolas** [xmtp/example-notification-server-go#44]
### Describe the bug

If a message matches multiple subscriptions, if any of the delivery services fail to deliver the message we should not error out of the whole process. Instead we should log a warning and continue with the rest of the subscriptions.

**Comment by bwcDvorak** [comment]
Unsure if it's feasible, but the partner that's affected by this suggests we consider retry mechanisms and or a dead letter queue

**Comment by neekolas** [comment]
Fixed by https://github.com/xmtp/example-notification-server-go/pull/46

**Comment by neekolas** [comment]
I'd suggest to the partner that retries or a dead letter queue should be implemented as part of the delivery service, which are customizable by the integrator.

Both are a good idea, but probably out of scope for the example server.

**Comment by marcomele** [comment]
Partner agrees, thank you for the quick fix :)
